# Generated by Django 4.2.7 on 2023-11-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardar_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_del_video', models.IntegerField(null=True)),
                ('video_name', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=5)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
