# Generated by Django 4.2.7 on 2023-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_guardar_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(null=True)),
                ('id_video', models.IntegerField(null=True)),
            ],
        ),
    ]
